Creating arrays and displaying it's dimension:

In [9]:
# To create a numpy array, we can use the function np.array()
import numpy as np
a= np.array([1,2,3])
print(a)
print("The dimension of the array is: ",a.ndim)    # 'ndim' shows the dimension of the array

[1 2 3]
1


Array:

In [33]:
import numpy as np
x=[1,2,3,4]
y=np.array(x)
y          # if we just want to print the array elements, then we use print function, else we just simply write the var name representing that array.
print("The dimension of the array is: ",y.ndim)

The dimension of the array is:  1


In [34]:
# taking the array elements as a user input
list=[]       
for i in range(5):
    array=int(input("Enter the array elements: "))
    list.append(array)
print(np.array(list))

Enter the array elements:  1
Enter the array elements:  2
Enter the array elements:  3
Enter the array elements:  4
Enter the array elements:  5


[1 2 3 4 5]


In [35]:
# 2-D array
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print("The dimension of the array is: ",x.ndim)

[[1 2 3 4]
 [5 6 7 8]]
The dimension of the array is:  2


In [36]:
# 3-D array
y=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
y
print(y.ndim)

# y=np.array([1,2,3],ndmin=3)
# print(y)

3


In [41]:
n=np.array([1,2,3,4],ndmin=10)   # 'ndmin' function is used to give the dimension
n                                # 'ndim' shows the dimension of the array
print("The dimension of the array is: ",n.ndim)

The dimension of the array is:  10
