### Creating NumPy arrays with random numbers:

#### 1) rand(): used to generate a random value b/w 0 to 1.

In [2]:
import numpy as np
a=np.random.rand(2)    #  for 1-d array, we just call the random module and then we provide the desired function, 
a                      # and in bracket we specify the number of values we want.

array([0.01670088, 0.69227497])

In [3]:
b=np.random.rand(2,5)      # for 2-D array, we just specify the dimension (rows x col) inside rand
b

array([[0.32607742, 0.57859909, 0.62505899, 0.71511205, 0.97149278],
       [0.68464965, 0.21688499, 0.5322242 , 0.33039404, 0.88178704]])

#### 2) randn(): 
- used to generate a random value close to zero.
- this may return positive or negative numbers as well.

In [4]:
a=np.random.randn(2)
a

array([-1.72038904,  0.10714601])

In [15]:
b=np.random.randn(4,3)
print(b)

[[ 1.03479234  0.31477288  0.96337752]
 [ 1.0156692  -2.14010817  0.4793107 ]
 [ 1.34506956  0.70147427 -0.72127289]
 [-2.60742349  1.82449686 -0.76625646]]


#### 3) ranf():
- used for doing random sampling in numpy.
- returns an array of specified shape and fills it with random float in the half open interval [0.0,1.0).

In [20]:
a=np.random.ranf(4)   # only generates a random number b/w 0 and 1 
a                     # here, min and max are pre-defined

array([0.17470251, 0.50027684, 0.08834456, 0.67388893])

#### 4) randint(): 
- used to generate a random number b/w a given range.
- var=np.random.randint(min,max,total)

In [34]:
a=np.random.randint(1,10,5)   # generates any random number sequence
print(a)                  

[8 1 1 3 5]


In [33]:
b=np.random.randint(1,100,10)
print(b)

[85 28 24 55 93 44 41 88 17 76]
