### Addition of arrays :

In [2]:
import numpy as np
a=np.array([1,2,3,4])    # for 1-D array, we specify a number by which we want each element to be added in that array
add= a + 2   
print(add)

[3 4 5 6]


In [3]:
a=np.array([1,2,3,4])  
add= np.add(a,2)  
print(add)

[3 4 5 6]


In [5]:
# the same task can be performed as
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
var_add = a+b
print(var_add)

[ 6  8 10 12]


In [4]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
var_add = np.add(a,b)
print(var_add)

[ 6  8 10 12]


### Subtraction of arrays:

In [6]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
var_subtract = a+b
print(var_add)

[ 6  8 10 12]


In [7]:
# 2-D array:
import numpy as np
a=np.array([1,2,3,4],ndmin=2)   
b=np.array([5,6,7,8],ndmin=2)
var_subtract= np.add(a,b)   
print(var_subtract)

[[ 6  8 10 12]]


### Multiplication of arrays:

In [8]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
var_mul = a*b
print(var_mul)

[ 5 12 21 32]


In [9]:
# 2-D array:
import numpy as np
a=np.array([1,2,3,4],ndmin=2)   
b=np.array([5,6,7,8],ndmin=2)
var_mul= np.multiply(a,b)   
print(var_mul)

[[ 5 12 21 32]]


### Division of arrays:

In [10]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
var_div = a/b
print(var_div)

[0.2        0.33333333 0.42857143 0.5       ]


In [11]:
# 3-D array:
a=np.array([1,2,3,4],ndmin=3)
b=np.array([5,6,7,8],ndmin=3)
var_div = np.divide(a,b)
print(var_div)

[[[0.2        0.33333333 0.42857143 0.5       ]]]


### Modulus of two arrays:

In [12]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
var_mod = a%b
print(var_mod)

[1 2 3 4]


In [13]:
a=np.array([1,2,3,4],ndmin=2)
b=np.array([5,6,7,8],ndmin=2)
var_mod = np.mod(a,b)
print(var_mod)

[[1 2 3 4]]


### Power of  two arrays:

In [14]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
var_power = a**b
print(var_power)

[    1    64  2187 65536]


In [15]:
a=np.array([1,2,3,4],ndmin=3)
b=np.array([5,6,7,8],ndmin=3)
var_power = np.power(a,b)
print(var_power)

[[[    1    64  2187 65536]]]


### Reciprocal of an array:

In [21]:
a=np.array([1,2,3,4])
var_invert = 1/a
print(var_invert)

[1.         0.5        0.33333333 0.25      ]


In [22]:
a=np.array([1,2,3,4])
var_invert = np.reciprocal(a)
print(var_invert)

[1 0 0 0]
