### Iterating Numpy arrays:

#### Method 1: by using 'for' loop

##### for 1-D array:

In [20]:
import numpy as np
a=np.array([1,2,3,4,5,6])
for i in a:
    print(i)

1
2
3
4
5
6


##### for 2-D array:

In [21]:
b=np.array([[1,2,3],[4,5,6]])
for i in b:
        print(i)

[1 2 3]
[4 5 6]


In [22]:
# if we don't want those two rows to be printed, then we use nested 'for' loop
b=np.array([[1,2,3],[4,5,6]])
for i in b:
    for j in i:
        print(j)

1
2
3
4
5
6


##### for 3-D array:

In [23]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in c:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in c:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9


#### Method 2: by using the function 'nditer'

In [35]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(c):                  # we use 'nditer' function to iterate over a given array
    print(i)                                                 

1
2
3
4
5
6
7
8
9


In [36]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in np.nditer(c, flags=["buffered"],op_dtypes=["S"]):    # here, we are changing the data types using the op_dtypes=["new_data.type"]
    print(i)                                                  # the flags= "buffered" here indicates that a temporary buffer is created to store the new array of another data type

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'


In [33]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i,d in np.ndenumerate(c):      # if we want index no. along with the data, then we use 'ndenumerate' function to do so
    print(i,d)                                                 

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
