### Joining of arrays:

for 1-D array:

In [23]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.concatenate((a,b)))

[1 2 3 4 5 6 7 8]


for 2-D array:

In [24]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[1,3,5,7],[2,4,6,8]])
print(np.concatenate((a,b), axis=0))

[[1 2 3 4]
 [5 6 7 8]
 [1 3 5 7]
 [2 4 6 8]]


for 3-D array:

In [25]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b=np.array([[[2,4,6],[3,6,9],[4,8,12]]])
print(np.concatenate((a,b), axis=1))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [ 2  4  6]
  [ 3  6  9]
  [ 4  8 12]]]


In [26]:
# we can also join two arrays by using 'stack' function
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
b=np.array([[[2,4,6],[3,6,9],[4,8,12]]])
# print(np.stack((a,b), axis=1))
print(np.vstack((a,b)))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 2  4  6]
  [ 3  6  9]
  [ 4  8 12]]]


### Splitting of an array:

In [31]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.split(a,5))

[array([1]), array([2]), array([3]), array([4]), array([5])]


In [36]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.split(b,3))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [41]:
c=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
# print(np.split(c,3))

ValueError: array split does not result in an equal division