#### Searching in numpy arrays:

In [21]:
# searches for an element and returns it's position
import numpy as np
a=np.array([[1,2,3,4,2],[1,3,5,7,2]])
b=np.where(a==2)
print(b)
b=np.where(a==2)
print(b)

(array([0, 0, 1], dtype=int64), array([1, 4, 4], dtype=int64))
(array([0, 0, 1], dtype=int64), array([1, 4, 4], dtype=int64))


In [22]:
a=np.array([[1,3,6,3,2],[1,3,5,7,7]])
b=np.where(a==3)
print(b)

(array([0, 0, 1], dtype=int64), array([1, 3, 1], dtype=int64))


#### Inserting in sorted array:

In [24]:
# inserts the provided value in the given array in the sorted order
x=np.array([1,2,4,5,9,6,2])
print(np.searchsorted(x,5, side="right"))

4


#### Sorting an array:

In [27]:
# arranges the given array in ascending order
a=np.array([7,1,6,3,9,0,2,6])
b=np.sort(a)
print(b)

[0 1 2 3 6 6 7 9]


In [29]:
# 2-D array:
a=np.array([[9,6,2,7,8],[1,3,0,2,6]])
print(np.sort(a))

[[2 6 7 8 9]
 [0 1 2 3 6]]


#### Filtering an array:

In [33]:
# here, we specify the elements which we want, as a boolean value within a list
a=np.array([1,2,3,4,5,6])
b=[False,True,False,False,True,False]
print(a[b])

[2 5]
