#### 1) Shuffle:

In [12]:
# randomly shuffles the array
import numpy as np
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[4 5 2 3 1]


#### 2) Unique:

In [16]:
# only returns the elements which are repeated
a=np.array([1,2,3,4,1,4,6,2,3,4])
b=np.unique(a, return_index=True, return_counts=True)
print(b)

(array([1, 2, 3, 4, 6]), array([0, 1, 2, 3, 6], dtype=int64), array([2, 2, 2, 3, 1], dtype=int64))


#### 3) Resize:

In [21]:
# resizes the given array
a=np.array([1,2,3,4,5,6])
b=np.resize(a,(2,2))
print(b)

[[1 2]
 [3 4]]


#### 4) Flatten:

In [22]:
# converts the given array in 1-D
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.flatten()
print(b)

[1 2 3 4 5 6 7 8]


#### 5) Ravel:

In [23]:
# converts the given array in 1-D
a=np.array([[1,2,3,4],[5,6,7,8]])
b=a.ravel()
print(b)

[1 2 3 4 5 6 7 8]
