#### Inserting an element in numpy array:

In [5]:
import numpy as np
a=np.array([1,2,3,4])
print(np.insert(a,4,6))      # np.insert(variable_name,(index),value_to_be_inserted)

[1 2 3 4 6]


In [9]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(np.insert(a,4,5, axis=1))   

[[1 2 3 4 5]
 [5 6 7 8 5]]


In [20]:
a=np.array([[1,2,3,4],[5,6,7,8]])            # must be 2-D array with same no. of cols
print(np.append(a,[[9,10,11,12]], axis=0))   # append as a new row

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
a=np.array([[1,2,3,4],[5,6,7,8]])        # must be 2-D array with same no. of rows
print(np.append(a,[[9],[10]], axis=1))   # append as a new column

[[ 1  2  3  4  9]
 [ 5  6  7  8 10]]


#### Deleting an element from numpy arrays:

In [22]:
a=np.array([1,2,3,4])
print(np.delete(a,2))        # np.delete(variable_name,index_no)

[1 2 4]


In [26]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(np.delete(a,1,axis=0))

[[1 2 3 4]]
