In [5]:
a= np.array([[1,2,3,4],[5,6,7,8]])
print(type(a))

<class 'numpy.ndarray'>


#### Matrix:

In [6]:
import numpy as np
a= np.matrix([[1,2,3,4],[5,6,7,8]])
print(type(a))

<class 'numpy.matrix'>


In [11]:
a=np.matrix([[1,2,3,4],[5,6,7,8]])
b=np.matrix([[1,2,3,4],[5,6,7,8]])
print(a+b)
# Addition of two matrices is same as that with arrays

[[ 2  4  6  8]
 [10 12 14 16]]


In [17]:
a=np.matrix([[1,2],[5,6]])        
b=np.matrix([[1,2,3,4],[5,6,7,8]])
print(a*b)
print(a.dot(b))
# for matrix multiplication, no. of columns in 'a' must match the no. of rows in 'b'
# here we have (2,2) and (2,4) matrix

[[11 14 17 20]
 [35 46 57 68]]
[[11 14 17 20]
 [35 46 57 68]]


#### Functions of a matrix:

##### 1) Transpose of a matrix:

In [25]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])     # (2 rows, 5 cols)
print(a.T)                                 # (5 rows, 2 cols)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


##### 2) Swap the axis of a matrix:

In [29]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])    
print(np.swapaxes(a,1,0))                       # np.swapaxes(var_name, indexno.of_the_array, result_array)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


##### 3) Inverse of a matrix:

In [40]:
a=np.matrix([[1,2],[3,4]])
print(np.linalg.inv(a))
# provided the matrix is square

[[-2.   1. ]
 [ 1.5 -0.5]]


##### 4) Power of a matrix:

In [46]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(np.linalg.matrix_power(a,2))           # np.linalg.matrix_power(varname, power)
# provided the matrix is square

[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]


##### 5) Determinant of a matrix:

In [49]:
a=np.array([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004
